[phases.setup]
nixpkgsArchive = "51ad838b03a05b1de6f9f2a0fffecee64a9788ee"
nixPkgs = ["nodejs_22", "python3", "gcc", "gnumake"]

[phases.install]
commands = [
  "npm install"
]

[phases.build]
commands = [
    "npx prisma generate",
  "npx prisma migrate deploy",
  "npm run build"
]

[variables]
NIXPACKS_NODE_VERSION = "22"

[start]
cmd = "source .env && node .output/server/index.mjs"
